import {createRoot} from 'react-dom/client';
import {useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {Wallet,LogOut,Users,Handshake,PieChart,Repeat2,ShieldCheck,Smartphone,PiggyBank} from 'lucide-react';
import Dashboard from './dashboard';
import Install from './install';
import {Button} from './components/ui/button';
import {Input} from './components/ui/input';
import {supabase,configured,homeUrl,apiFetch} from './api';
import './style.css';
function App(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[invite,setInvite]=useState(''),[dashboardKey,setDashboardKey]=useState(0);
 useEffect(()=>{const candidate=new URLSearchParams(location.hash.slice(1)).get('invite');if(candidate&&/^[a-f0-9]{64}$/.test(candidate)){sessionStorage.setItem('tasca-invite',candidate);history.replaceState(null,'',location.pathname+location.search);}setInvite(sessionStorage.getItem('tasca-invite')||'');if(!supabase){setLoading(false);return;}let live=true;supabase.auth.getSession().then(({data,error})=>{if(live){setSession(data.session);setLoading(false);if(error)setError('Accesso non riuscito. Riprova.');}});const {data}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setMode('update');setLoading(false);});return()=>{live=false;data.subscription.unsubscribe();};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');setMessage('');try{let result;if(mode==='login')result=await supabase.auth.signInWithPassword({email,password});else if(mode==='register')result=await supabase.auth.signUp({email,password,options:{data:{name:name.trim()},emailRedirectTo:homeUrl()}});else if(mode==='resend')result=await supabase.auth.resend({type:'signup',email,options:{emailRedirectTo:homeUrl()}});else if(mode==='reset')result=await supabase.auth.resetPasswordForEmail(email,{redirectTo:homeUrl()});else result=await supabase.auth.updateUser({password});if(result.error)throw result.error;if(mode==='register'||mode==='resend')setMessage('Controlla la posta e conferma il tuo indirizzo, poi torna qui per accedere.');if(mode==='reset')setMessage('Se l’indirizzo è registrato, riceverai un link per scegliere una nuova password.');if(mode==='update'){setMode('login');setPassword('');setMessage('Password aggiornata.');}}catch(e:any){setError(e.code==='invalid_credentials'?'Email o password non corrette.':e.code==='email_not_confirmed'?'Conferma prima il tuo indirizzo email.':e.code==='over_email_send_rate_limit'?'Troppe richieste email. Attendi qualche minuto e riprova.':e.code==='weak_password'?'Scegli una password più lunga e difficile da indovinare.':'Operazione non riuscita. Riprova tra poco. Se non arrivano email, contatta chi gestisce questa copia di Tasca.');}finally{setBusy(false);}}
 async function join(){setBusy(true);setError('');try{const res=await apiFetch('/api/sharing',{method:'POST',body:JSON.stringify({action:'accept',token:invite})});const data=await res.json();if(!res.ok)throw Error(data.error);sessionStorage.removeItem('tasca-invite');setInvite('');setDashboardKey(n=>n+1);setMessage('Conto condiviso aggiunto. Lo trovi in Conti.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 if(!configured)return <main className="auth-wrap"><div className="auth-card"><Wallet size={36}/><h1>Tasca è quasi pronta.</h1><p>Chi gestisce questa copia deve completare il collegamento per gli account e i conti condivisi.</p><p>Apri la guida <b>docs/PUBBLICARE.md</b> nella cartella del progetto. Dopo la configurazione, qui compariranno “Accedi” e “Crea account”.</p><p>Nessun conto o movimento viene salvato in questa schermata.</p></div></main>;
 if(loading)return <div className="empty">Apertura di Tasca…</div>;
 if(session&&mode!=='update')return <><div className="session-bar"><span>{session.user.email}</span><Button variant="ghost" onClick={async()=>{setError('');const {error}=await supabase!.auth.signOut();if(error)setError('Uscita non riuscita. Riprova con una connessione attiva.');else {setSession(null);setMessage('');setPassword('');}}}><LogOut size={16}/> Esci</Button></div>{invite&&<section className="invite-banner"><Users/><div><b>Hai ricevuto un invito a un conto.</b><p>Accettando potrai vedere e modificare i movimenti di quel conto. Accetta solo inviti da persone che conosci.</p></div><Button disabled={busy} onClick={join}>Accetta invito</Button><Button variant="ghost" onClick={()=>{sessionStorage.removeItem('tasca-invite');setInvite('');}}>Ignora</Button></section>}{message&&<p className="feedback" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}<Dashboard key={session.user.id+dashboardKey}/></>;
 return <main className="auth-wrap con-vetrina"><section className="vetrina">
  <div className="auth-brand"><Wallet/> tasca.</div>
  <h1 className="claim">I conti di casa, in due,<br/>senza doverseli ricordare.</h1>
  <p className="claim-sub">Entrate, spese e budget in un posto solo. Un conto condiviso con chi vuoi tu,
   e Tasca tiene il segno di chi ha pagato cosa — anche quando non si divide a metà.</p>
  <ul className="vetrina-punti">
   <li><span className="icon purple"><Handshake size={19}/></span><div><b>Conti condivisi, senza discussioni</b><span>Tu registri, l’altra persona vede. Il saldo «chi deve quanto a chi» si aggiorna da solo.</span></div></li>
   <li><span className="icon purple"><PieChart size={19}/></span><div><b>Dove finiscono i soldi</b><span>Categorie, budget mensile e rendiconto di fine anno da stampare.</span></div></li>
   <li><span className="icon purple"><Repeat2 size={19}/></span><div><b>Affitto e bollette non si scordano</b><span>Le ricorrenze tornano a ogni scadenza, da confermare con un tocco.</span></div></li>
   <li><span className="icon purple"><PiggyBank size={19}/></span><div><b>Obiettivi di risparmio</b><span>Vacanza o fondo imprevisti: quanto manca e quanto mettere via ogni mese.</span></div></li>
  </ul>
  <div className="vetrina-fiducia">
   <p><ShieldCheck size={16}/> <b>Gratis, senza pubblicità.</b> Tasca non si collega alla tua banca e non vende i tuoi dati a nessuno. I conti restano tuoi: li esporti o cancelli l’account quando vuoi.</p>
   <p><Smartphone size={16}/> <b>Si installa dal browser.</b> Nessuno store, nessun permesso strano: apri il link dal telefono e aggiungi l’icona alla schermata Home.</p>
  </div>
  <p className="vetrina-chiusura">Creata da una persona sola, in Italia, perché in casa nostra serviva. <a href={import.meta.env.BASE_URL+'privacy.html'} target="_blank" rel="noopener">Come tratto i dati</a></p>
 </section><section className="auth-card"><div className="auth-brand mobile-brand"><Wallet/> tasca.</div><h1>{mode==='register'?'Un posto per i tuoi conti.':mode==='reset'?'Recupera l’accesso':mode==='update'?'Scegli una nuova password':mode==='resend'?'Conferma la tua email':'Bentornato in Tasca.'}</h1><p>Il tuo account Tasca. Entrate, spese e conti di famiglia, anche da telefoni diversi.</p>{invite&&<p className="sharing-note">Il tuo invito è pronto. Accedi o crea un account, poi potrai accettarlo.</p>}{import.meta.env.VITE_GOOGLE_LOGIN==='true'&&mode!=='update'&&<Button className="save" variant="outline" disabled={busy} onClick={async()=>{setBusy(true);const {error}=await supabase!.auth.signInWithOAuth({provider:'google',options:{redirectTo:homeUrl()}});if(error){setError('Accesso con Google non disponibile. Riprova.');setBusy(false);}}}>Continua con Google</Button>}<form onSubmit={submit}>{mode==='register'&&<label>Il tuo nome<Input required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}{mode!=='update'&&<label>Email<Input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{!['reset','resend'].includes(mode)&&<label>Password<Input type="password" required minLength={mode==='login'?1:12} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/>{mode!=='login'&&<small>Almeno 12 caratteri. Puoi usare una frase facile da ricordare.</small>}</label>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="feedback">{message}</p>}<Button className="primary save" disabled={busy}>{busy?'Attendi…':mode==='login'?'Accedi':mode==='register'?'Crea account':mode==='update'?'Salva password':'Invia email'}</Button></form><div className="auth-links">{[['login','Ho già un account'],['register','Crea account'],['reset','Password dimenticata?'],['resend','Reinvia conferma email']].filter(([v])=>v!==mode).map(([v,label])=><button key={v} onClick={()=>{setMode(v);setError('');setMessage('');setPassword('');}}>{label}</button>)}</div><Install/><p className="meta">Nessun account ChatGPT o GitHub per chi usa l’app. Serve Internet per salvare e sincronizzare.<br/><a href={import.meta.env.BASE_URL+'privacy.html'} target="_blank" rel="noopener">Informativa privacy</a></p></section></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
