import {useState} from 'react';
import {Users,Copy,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {apiFetch,homeUrl} from './api';
export type Member={account_id:string,email:string,user_id:string|null};
export default function Sharing({account,members,refresh}:{account:{id:string,name:string},members:Member[],refresh:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function action(action:string,email?:string){setBusy(true);setError('');setNotice('');try{const r=await apiFetch('/api/sharing',{method:'POST',body:JSON.stringify({action,email,account_id:account.id})});const j=await r.json();if(!r.ok)throw Error(j.error);if(j.token)setLink(homeUrl()+'#invite='+j.token);if(action==='revoke'){setLink('');setNotice('Inviti non utilizzati annullati.');}await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <><Button variant="ghost" onClick={()=>setOpen(true)}><Users size={16}/> Condividi</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>Condividi {account.name}</DialogTitle><DialogDescription>Crea un link e invialo alla persona con cui vuoi gestire questo conto. Potrà vedere, aggiungere, modificare ed eliminare i suoi movimenti e quelli del conto. Gli altri conti restano privati.</DialogDescription><Button disabled={busy} onClick={()=>action('invite')}>Crea link di invito</Button>{link&&<div className="sharing-note"><label>Link personale<input readOnly value={link} onFocus={e=>e.target.select()}/></label><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(link);setNotice('Link copiato. Ora incollalo in un messaggio.');}catch{setNotice('Seleziona il link e usa Copia dal menu del telefono.');}}}><Copy size={16}/> Copia link</Button><p>Vale 48 ore e si usa una sola volta. Chi lo riceve deve accedere a Tasca e accettare l’invito. Condividilo solo con la persona scelta.</p></div>}<Button disabled={busy} variant="ghost" onClick={()=>action('revoke')}>Annulla tutti gli inviti non utilizzati</Button>{members.map(m=><div className="member-row" key={m.user_id}><span>{m.email}</span><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" aria-label={'Rimuovi '+m.email}><Trash2 size={16}/></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>Rimuovere il partecipante?</AlertDialogTitle><AlertDialogDescription>Perderà l’accesso al conto. I movimenti già registrati resteranno.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction onClick={()=>action('remove',m.email)}>Rimuovi</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>)}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="error">{error}</p>}</DialogContent></Dialog></>;
}
